apiVersion: v1
kind: BuildConfig
metadata:
  name: custom-jenkins-build
spec:
  source:                       
    type: Git
    git:
      uri: https://github.com/kharyam/ocp-all-in-one
    contextDir: "ansible/kmendez.ocp-demo/files/jenkins-ocp"
  strategy:                     
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins:latest
        namespace: openshift
    type: Source
  output:                       
    to:
      kind: ImageStreamTag
      name: custom-jenkins:latest
