---
# tasks file for kmendez.ocp-demo
- name: "Get OpenShift Version"
  shell: oc version | grep 'oc v'
  register: oc_version
- name: "Fix dnsmasq networking in OCP 3.6 ({{ oc_version.stdout }})"
  block:
    - name: Fix 99-origin-dns.sh in OCP 3.6 ({{ oc_version.stdout }})
      copy:
        src: 99-origin-dns.sh
        dest: /etc/NetworkManager/dispatcher.d/99-origin-dns.sh
        backup: yes
    - name: Restart networking
      service:
        name: network
        state: restarted
  when: 'oc_version.stdout | search("3.6")'

- name: "Install / Configure Demo"
  block:
    - name: Gratuitous logo
      debug:
       msg: "{{ demo_logo.split('\n') }}"

                                                                  
    - name: Grant cluster admin to admin user
      command: "oc adm policy add-cluster-role-to-user cluster-admin admin {{ openshift_creds }}"
    - name: Create docker group
      group:
        name: docker
        state: present
    - name: Create OpenShift User ( {{ openshift_user }} )
      user: 
        name: "{{ openshift_user }}"
        comment: "OpenShift User"
        groups: "{{ openshift_user_groups }}"
        state: present
        append: yes
    - name: Create Kube Ops View project
      command: "oc new-project ocp-ops-view {{ openshift_creds }}"
      register: kube_ops
      ignore_errors: true
    - name: Initialize Kube Ops View Project
      command: "{{ item }} {{ openshift_creds }} -n ocp-ops-view"
      with_items:
        - oc create sa kube-ops-view
        - oc adm policy add-scc-to-user anyuid -z kube-ops-view
        - oc adm policy add-cluster-role-to-user cluster-admin -z kube-ops-view
        - oc apply -f https://raw.githubusercontent.com/raffaelespazzoli/kube-ops-view/ocp/deploy-openshift/kube-ops-view.yaml
        - oc expose svc kube-ops-view        
      when: kube_ops.rc == 0
    - name: Copy PV directory creation script
      template:
        src: create_pv_dirs.sh.j2
        dest: /tmp/create_pv_dirs.sh
        owner: root
        group: root
        mode: '0700'
    - name: Create PV directories
      command: /tmp/create_pv_dirs.sh
    - name: Copy PV creation script
      template:
        src: create_pvs.sh.j2
        dest: /tmp/create_pvs.sh
        owner: root
        group: root
        mode: '0700'
    - name: Creating {{ openshift_num_pvs }} PVs...
      command: /tmp/create_pvs.sh        
    - name: Limit metrics resources
      command: "{{ item }} {{ openshift_creds }} -n openshift-infra"
      with_items:
        - oc env rc/hawkular-cassandra-1 MAX_HEAP_SIZE=512M 
        - oc env rc/hawkular-cassandra-1 NEW_HEAP_SIZE=100M
        - oc set resources rc/hawkular-metrics --requests=cpu=500m,memory=256Mi --limits=cpu=2000m,memory=1536Mi
      ignore_errors: true
    - name: Check if PVC was created for metrics
      shell: oc get pvc -n openshift-infra {{ openshift_creds }} | grep -v "No resources"
      register: pvc_exists
      ignore_errors: true
    - name: Bind PVC for metrics, if not bound
      command: oc volume rc/hawkular-cassandra-1 --overwrite --mount-path=/cassandra_data --type=persistentVolumeClaim --add --claim-size=10Gi --name=cassandra-data {{ openshift_creds }} -n openshift-infra
      when: pvc_exists.rc != 0
    - name: Restart cassandra / metrics
      command: "{{ item }} {{ openshift_creds }} -n openshift-infra"
      with_items:      
        - oc scale rc/hawkular-cassandra-1 --replicas=0 
        - oc scale rc/hawkular-metrics --replicas=0
        - oc scale rc/hawkular-cassandra-1 --replicas=1
        - oc scale rc/hawkular-metrics --replicas=1 
    - name: Grant anyuid to pqc-support project
      command: oc adm policy add-scc-to-user anyuid -z default -n pqc-support {{ openshift_creds }}
    - name: Copy registy PVC creation file
      copy:
        src: registry-pvc.yml
        dest: /tmp/registry-pvc.yml
    - name: Create PVC for registry
      command: oc create -f /tmp/registry-pvc.yml {{ openshift_creds }} -n default
      ignore_errors: true
    - name: Attach PVC for registry
      command: oc volume deploymentconfigs/docker-registry --add --name=registry-storage -t pvc --claim-name=registry-pvc --overwrite -n default {{ openshift_creds }}
      ignore_errors: true
    - name: Get DC for logging      
      shell: "oc get dc -n logging {{ openshift_creds }} | grep logging-es | awk '{print $1}'"
      register: logging_dc
    - name: Attach PVC for logging ( {{ logging_dc.stdout }} )
      command: "oc volume dc/{{ logging_dc.stdout }} --add --name=elasticsearch-storage -t pvc --claim-name=logging-es-1 --overwrite {{ openshift_creds }} -n logging"
      ignore_errors: true
    - name: Copy demo service file
      template:
        src: demo.service.j2
        dest: /etc/systemd/system/demo.service
    - name: Copy project initialization file
      template:
        src: projects.sh.j2
        dest: /home/{{ openshift_user }}/projects.sh
        owner: "{{ openshift_user }}"
        group: "{{ openshift_user }}"
        mode: '0700'
    - name: Copy PQC Template Files
      copy:
        src: "{{ item }}"
        dest: /home/{{ openshift_user }}/pqc_templates/
        owner: "{{ openshift_user }}"
        group: "{{ openshift_user }}"
        mode: '0664'
      with_fileglob:
        - pqc_templates/*
    - name: Create SonarQube Directory
      file:
        path: "/home/{{ openshift_user }}/sonarqube"
        state: directory
    - name: Copy SonarQube Docker File
      copy:
        src: sonarqube/Dockerfile
        dest: "/home/{{ openshift_user }}/sonarqube/Dockerfile"
    - name:  Copy Custom Jenkins Instance Files
      copy:
        src: "{{ item }}"
        dest: /home/{{ openshift_user }}/ocp-jenkins/
        owner: "{{ openshift_user }}"
        group: "{{ openshift_user }}"
        mode: '0664'
      with_fileglob:
        - jenkins-ocp/*        
    - name: Reload services (just in case)
      command: systemctl daemon-reload
    - name: Download EAP Docker images
      docker_image: 
        name: "{{ item }}"
        state: present
      with_items: "{{ eap_images }}"
    - name: Enable and start demo service
      service:
        name: demo
        state: started
        enabled: yes
      async: 600
      poll: 10
    - name: Attach PVC to Jenkins
      command: oc volume dc/custom-jenkins --add --name=custom-jenkins-volume-1 -t pvc --claim-size=1G --overwrite --claim-name=pvc-jenkins -n pqc-support {{ openshift_creds }}
#      ignore_errors: true
    - name: Update jenkins account
      command: "{{ item }} {{ openshift_creds }}"
      with_items:
        - oc create sa jenkins -n pqc-support
        - oc policy add-role-to-user edit system:serviceaccount:pqc-support:jenkins -n pqc-dev
        - oc policy add-role-to-user edit system:serviceaccount:pqc-support:jenkins -n pqc-test
        - oc policy add-role-to-user edit system:serviceaccount:pqc-support:jenkins -n pqc-prod
        - oc adm policy add-scc-to-user privileged -z jenkins -n pqc-support
        - oc adm policy add-scc-to-user anyuid  -z jenkins -n pqc-support
        - oc policy add-role-to-user edit system:serviceaccount:pqc-support:default -n pqc-dev
        - oc policy add-role-to-user edit system:serviceaccount:pqc-support:default -n pqc-test
        - oc policy add-role-to-user edit system:serviceaccount:pqc-support:default -n pqc-prod
        - oc adm policy add-scc-to-user privileged -z default -n pqc-support
        - oc adm policy add-scc-to-user anyuid  -z default -n pqc-support
      ignore_errors: true
    - name: Clone Jenkins slave SCAP image
      git:
        repo: 'https://github.com/kharyam/jenkins.git'
        dest: /tmp/scap
    - name: Login to OCP docker repository
      shell: oc login https://{{ inventory_hostname }}:8443 -u admin -p admin && docker login -u $(oc whoami) -p $(oc whoami -t) docker-registry.default.svc:5000
    - name: Build Jenkins slave SCAP image and push into OCP
      docker_image:
        path: /tmp/scap/slave-scap
        dockerfile: Dockerfile.rhel7
        name: docker-registry.default.svc:5000/openshift/scap-slave:latest
        tag: latest
        push: yes
        state: present
    - name: Copy eclipse che install script
      template:
        src: eclipse-che/install.sh.j2
        dest: /tmp/install.sh
        owner: root
        group: root
        mode: '0700'
    - name: Install jq
      get_url: 
        url: "{{ jq_download }}"
        dest: /usr/bin/jq
        mode: 0555
    - name: Install eclipse che
      command: /tmp/install.sh
    - name: Configure eclipse che users
      command: "{{ item }} {{ openshift_creds }} -n eclipse-che"
      with_items:
        - oc adm policy add-scc-to-user anyuid -z default 
        - oc adm policy add-scc-to-user anyuid -z che
        - oc adm policy add-scc-to-user privileged -z default
        - oc adm policy add-scc-to-user privileged -z che
      ignore_errors: true
    - name: Update che config map
      command: "oc patch cm/che -p '{ \"data\": {\"che-openshift-secure-routes\" : \"false\", \"che-secure-external-urls\": \"false\", \"che.docker.server_evaluation_strategy.custom.external.protocol\": \"http\"} }'"
    - name: Expose che as http
      command: "{{ item }} -n eclipse-che {{ openshift_creds }}"
      with_items:
        - oc delete route che
        - oc expose svc/che-host --name=che --hostname=che-eclipse-che.apps.{{ ansible_default_ipv4.address }}.xip.io
      ignore_errors: true
    - name: Patch che DC, set SCC privileged to true
      command: "oc patch dc/che --patch='{\"spec\": {\"template\": {\"spec\": {\"containers\": [  {\"name\":\"che\",\"securityContext\": { \"privileged\": true }}]}}}}' -n eclipse-che {{ openshift_creds }}"
    - name: Capture gogs pv location
      shell: "oc get pvc --all-namespaces  {{ openshift_creds }} | grep gogs | awk '{print $4}'"
      register:
        gogs_pv
    - name: Remove existing gogs data
      command: rm -fr ~openshift/pvs/{{ gogs_pv.stdout }}/*
    - name: "Extract gogs data (user: developer password: Welcome1!)"
      unarchive:
        src: gogs-pvc.tar.gz
        dest: ~openshift/pvs/{{ gogs_pv.stdout }}
    - name: Restart gogs
      command: oc rollout latest gogs -n pqc-support {{ openshift_creds }}
